config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  # resources :companies, only: %w[index new create]
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/team', to: 'pages#team', as: 'team'
  resources :cars, only: %w[index show] do
    resources :reservations, only: %w[create destroy]
  end
  resources :reservations, only: %w[update]
  resources :users, only: [:show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :company
  has_many :reservations
  has_many :feedbacks, through: :reservations
  has_one_attached :photo
  validates :model, :color, :plate_number, presence: true
  validates :company, presence: true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :company
  has_many :messages, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  geocoded_by :address
  has_many :chatrooms, dependent: :destroy
  has_many :cars
  has_many :users, dependent: :destroy
  has_one_attached :logo
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :reservation
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user
  validates :content, presence: true
  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :car
  belongs_to :user
  has_one :feedback, dependent: :destroy

  validates :start_date, :end_date, presence: true
  validates :kilometers, presence: true
  validates :kilometers, numericality: { greater_than: 0 }, if: :kilometers_changed? && :persisted?

  before_update :calculate_kilometers_done
  accepts_nested_attributes_for :feedback

  private

  def calculate_kilometers_done
    last_reservation = car.reservations.where(done: true).order(updated_at: :desc).limit(1).first
    last_known_kilometers = last_reservation ? last_reservation.kilometers : car.kilometers
    self.kilometers_done = (kilometers - last_known_kilometers)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :company
  has_many :reservations
  has_many :feedbacks, through: :reservations
  has_one_attached :avatar

  def pending_reservations
    reservations.where(done: false).order('start_date DESC')
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "https://www.sharethecars.me/" }
  end

  private

  def set_company
    @user_company = current_user.company
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_company

  def index
    @cars = @user_company.cars

    return unless params[:start_date].present? && params[:end_date].present?

    @start_date = Date.parse(params[:start_date])
    @end_date = Date.parse(params[:end_date])

    @cars = @cars.where.not(id: Reservation.where("start_date <= ? AND end_date >= ?", @end_date, @start_date).select(:car_id))
  end

  def show
    @car = Car.find(params[:id])
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @reservation = Reservation.new
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
    @messages = @chatroom.messages.order(created_at: :desc).limit(30)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = @chatroom.messages.new(message_params)
    @message.user = current_user

    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "shared/message", locals: { message: @message }),
        sender_id: @message.user.id,
        avatar_url: @message.user.avatar.attached? ? url_for(@message.user.avatar) : nil,
        sender_name: @message.user.full_name,
        profile_url: user_path(@message.user)
      )
      head :ok
    else
      @messages = @chatroom.messages.order(created_at: :desc).limit(30)
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @car_availables_tomorrow =
      current_user.company.cars
                  .where.not(id: Reservation.where("start_date <= ? AND end_date >= ?", Date.tomorrow, Date.tomorrow)
                  .select(:car_id))
                  .count
    @average_kilometers = current_user.reservations.average(:kilometers).to_i
    @feedback = Feedback.new
  end

  def team
    @company = current_user.company
    @team = User.where(company: @company)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_car, only: [:create]

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.car = @car
    @reservation.kilometers = 0
    @reservation.save!
    redirect_to dashboard_path, notice: "Votre réservation a bien été prise en compte."
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.done = true
    @reservation.update(reservation_params)
    @reservation.create_feedback(feedback_params)
    redirect_to dashboard_path, notice: "Votre réservation a bien été clôturée."
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to dashboard_path
  end

  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def feedback_params
    params.require(:feedback).permit(:comment)
  end

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date, :kilometers)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
    @user = User.find(params[:id])
    @feedbacks = @user.feedbacks.order(created_at: :desc).limit(5)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper

 def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
 end


 def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
 end


 def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
 end
end

app/views/cars/_filter.html.erb
<%= simple_form_for '', url: cars_path, method: :get do |f| %>
  <div class="card bg-white rounded rounded-4">
    <div class="card-body p-3" data-controller="datepicker">
      <div class="row">
        <%= f.input :start_date,
            as: :hidden,
            id: "start_date",
            input_html: { class: "d-none", value: @start_date, data: { datepicker_target: "container" }}
        %>
        <%= f.input :end_date,
            as: :hidden,
            input_html: { value: @end_date },
            id: "end_date"
        %>
      </div>
      <div class="col-md-12 mt-2">
        <div class="text-center mt-3">
          <button type="button" class="btn btn-link d-block mx-auto" data-action="datepicker#reset">Réinitialiser les dates</button>
          <%= f.submit "Voir les voitures disponibles",  :class => "btn btn-primary px-4 rounded-3" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/_form.html.erb
<%= simple_form_for [@car, @reservation] do |f| %>
  <div class="card bg-white rounded rounded-4">
    <div class="card-body p-3" data-controller="datepicker" data-datepicker-dates-value="<%= @car.reservations.to_json %>">
      <div class="row">
        <%= f.input :start_date,
              as: :string,
              label: false,
              input_html: { value: @start_date, data: { datepicker_target: "container" }, id: "start_date", class: 'd-none text-center mx-auto' }
        %>
        <%= f.input :end_date,
              as: :hidden,
              input_html: {value: @end_date, id: "end_date"} %>
      </div>
      <div class="col-md-12 mt-2">
        <div class="text-center mt-3">
          <button type="button" class="btn btn-link d-block mx-auto" data-action="datepicker#reset">Réinitialiser les dates</button>
          <%= f.button :submit, "Réserver la voiture",  class: "btn btn-primary px-4 rounded-3" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/cars/index.html.erb
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-md-9">
      <% if @start_date.present? && @end_date.present? %>
        <% if @cars.present? %>
          <h1>Voitures disponibles du <span class="text-primary fw-bold"><%= l(@start_date, format: "%d/%m/%y") %></span> au <span class="text-primary fw-bold"><%= l(@end_date, format: "%d/%m/%y") %></span></h1>
        <% else %>
          <h1>Malheureusement, aucune voiture n'est disponibles du <span class="text-primary fw-bold"><%= l(@start_date, format: "%d/%m/%y") %></span> au <span class="text-primary fw-bold"><%= l(@end_date, format: "%d/%m/%y") %></span></h1>
        <% end %>
      <% else %>
        <h1>Voitures disponibles pour les employés de <%= @user_company.name %></h1>
      <% end %>
      <div class="row">
        <% @cars.each do |car| %>
          <div class="col-12 col-md-4 p-3">
            <%= link_to car_path(car, :start_date => @start_date, :end_date => @end_date), class:"text-decoration-none text-black" do %>
              <div class="card-trip">
                <%= cl_image_tag(car.photo.key, class: "w-100") %>
                <div class="card-trip-infos">
                  <div>
                    <h2 class="fs-5"><%= car.model %></h2>
                    <div class="d-flex gap-3 mt-2">
                      <span><i class="fas fa-palette"></i> <%= car.color %></span><br>
                      <span><i class="fas fa-rectangle-ad"></i> <%= car.plate_number %></span><br>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-3 position-relative">
      <div class="position-fixed">
        <%= render "filter" %>
      </div>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="container-fluid">
  <div class="row mt-3">
    <div class="col-md-9">
      <div class="card bg-white rounded rounded-4">
        <%= cl_image_tag(@car.photo.key, class: "w-100") %>
      </div>
      <div class="card-body py-3">
        <h1 class="card-title">
          <p><%= @car.model %></p>
        </h1>
        <div class="d-flex gap-3 mt-2">
          <span><i class="fas fa-palette"></i> <%= @car.color %></span><br>
          <span><i class="fas fa-rectangle-ad"></i> <%= @car.plate_number %></span><br>
        </div>
      </div>

      <div class="mt-4">
        <h2>Derniers commentaires</h2>
        <%= render "shared/feedbacks", feedbacks: @car.feedbacks %>
      </div>
    </div>
    <div class="col-md-3 position-relative">
      <div class="position-fixed">
        <canvas class="bg-white card p-3 mb-4" data-controller="kilometers-charts" data-kilometers-charts-reservations-value="<%= @car.reservations.to_json %>" data-kilometers-charts-base-kilometers-value="<%= @car.kilometers %>">
        </canvas>
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div class="container-fluid my-5">
  <div class="row">
    <div class="col-md-9 chatroom" data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
    data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
      <div data-controller="video-background-chatroom">
        <video autoplay loop muted playsinline class="chatroom-video-background" data-video-background-chatroom-target="video">
          <source src="https://i.gifer.com/fxk4.mp4" type="video/mp4">
          Votre navigateur ne supporte pas la balise vidéo.
        </video>
      </div>
      <div class="video-gradient"></div>
      <div class="d-flex text-center">
        <hr class="flex-grow-1 chatboxligne">
        <h1 class="px-2"><%= @chatroom.name %></h1>
        <hr class="flex-grow-1 chatboxligne">
      </div>
      <div class="messages" data-chatroom-subscription-target="messages">
        <% @messages.reverse_each do |message| %>
          <div class="message-row d-flex align-items-end <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
            <% unless message.sender?(current_user) %>
              <div class="px-2">
                <%= link_to user_path(message.user) do %>
                  <%= cl_image_tag(message.user.avatar.key, alt: message.user.full_name, class: "avatar", title: message.user.full_name, crop: :fill) if message.user.avatar.attached? %>
                <% end %>
              </div>
            <% end %>
            <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
              <%= render "shared/message", message: message %>
            </div>
            <% if message.sender?(current_user) %>
              <div class="px-2">
                <%= link_to user_path(message.user) do %>
                  <%= cl_image_tag(message.user.avatar.key, alt: message.user.full_name, class: "avatar", title: message.user.full_name, crop: :fill) if message.user.avatar.attached? %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="button-chatroom mt-3">
        <%= simple_form_for [@chatroom, @message] do |f| %>
          <%= f.input :content, label: false, placeholder: "Message...", input_html: { data: { chatroom_subscription_target: "messageInput" } } %>
        <% end %>
      </div>
    </div>
    <div class="utilisateur-chat col-md-2 pt-4">
      <div class="user-list-card pb-3">
        <div class="card-body">
          <div class="online-users">
            <h5 class="users-title">En ligne</h5>
            <div class="user-card online">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #ff6600;"></i>
                <p>Mayeul BRETON -<span class="user-status online"> En ligne</span></p>
              </div>
            </div>
            <div class="user-card online">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #ff6600;"></i>
                <p>Amaranthe LEMAIRE -<span class="user-status online"> En ligne</span></p>
              </div>
            </div>
            <div class="user-card online">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #ff6600;"></i>
                <p>Daniel GUASCO -<span class="user-status online"> En ligne</span></p>
              </div>
            </div>
          </div>
          <div class="offline-users mt-4">
            <h5 class="users-title">Hors ligne</h5>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Henri ROCHE -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Véronique ROBERT -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Frédéric PRÉVOST -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Ambroise FLEURY -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Althée VINCENT -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Zéphirine ROGER -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Guenièvre NOËL -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Aglaé ROLLAND -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
            <div class="user-card offline">
              <div class="user-info-chat">
                <i class="fa-solid fa-user me-2" style="color: #555555;"></i>
                <p>Turold MARCHAND -<span class="user-status offline"> Hors ligne</span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/feedbacks/_index.html.erb
<% feedbacks.each do |feedback| %>
  <div class="notification box-shadow border">
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag(current_user.avatar.key, crop: :fill, gravity: :face, class: "avatar-large") %>
    <% else %>
      <%= image_tag 'avatar.png', class:"avatar-large", width: 300 %>
    <% end %>
    <div class="notification-content">
      <p><small><%= feedback.reservation.user.first_name %> <%= feedback.reservation.user.last_name %></small></p>
      <p><%= feedback.comment %></p>
      <p><small>Il y a</small>  <%= time_ago_in_words(feedback.created_at) %></p>
    </div>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container-fluid">
  <div class="mt-3">
    <h1>Tableau de bord</h1>
    <div class="row mt-3">
      <%= render 'shared/dashboard_card', icon: 'hourglass-start', color: 'primary', text: 'Nombre de voitures que vous avez réservé', value: current_user.reservations.count %>
      <%= render 'shared/dashboard_card', icon: 'road', color: 'secondary', text: 'Kilomètrages moyen par réservations', value: "#{current_user.reservations.average(:kilometers_done) ? current_user.reservations.average(:kilometers_done) : '0'} km" %>
      <%= render 'shared/dashboard_card', icon: 'clock', color: 'success', text: 'Kilomètres total que vous avez effectué', value: "#{current_user.reservations.sum(:kilometers_done)} km" %>
      <%= render 'shared/dashboard_card', icon: 'car', color: 'info', text: 'Nombres de voitures disponible demain', value: @car_availables_tomorrow %>
    </div>
    <div class="row mt-5">
      <div class="col-md-12">
        <h2>Réservations en cours</h2>
        <div class="mt-3 table-responsive mx-n1 px-1 scrollbar">
          <table class="table fs-9 mb-0 border border-white table-light">
            <thead>
              <tr>
                <th class="bg-white">Véhicule</th>
                <th class="bg-white">Date d'emprunt</th>
                <th class="bg-white">Date de restitution</th>
                <th class="bg-white" style="width: 15%">Actions</th>
              </tr>
            </thead>
            <tbody class="list" id="table-latest-review-body">
              <% current_user.pending_reservations.each do |reservation| %>
                <tr class="hover-actions-trigger btn-reveal-trigger position-static">
                  <td class="align-middle">
                    <%= reservation.car.model %><br>
                    <small><i class="fas fa-rectangle-ad pe-1"></i> <%= reservation.car.plate_number %> <i class="ps-2 pe-1 fas fa-palette"></i><%= reservation.car.color %></small>
                  </td>
                  <td class="align-middle"><%= l reservation.start_date %></td>
                  <td class="align-middle"><%= l reservation.end_date %></td>
                  <td class="align-middle gap-3">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#voiture-<%= reservation.car.id %>">
                      Clôturer
                    </button>
                    <%= link_to 'Annuler', car_reservation_path(car_id: reservation.car_id, id: reservation.id), data: { turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr de vouloir annuler cette réservation ?' }, class: 'btn btn-link' %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
<% current_user.pending_reservations.each do |reservation| %>
  <div class="modal fade" id="voiture-<%= reservation.car.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Clôturer ma réservation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= simple_form_for reservation do |f| %>
          <div class="modal-body">
            <p>Vous êtes sur le point de clôturer votre réservation pour le véhicule "<%= reservation.car.model %>".<br>
              <br>
              Vous pouvez laisser un commentaire ci-dessous pour le suivi du véhicule. Merci de signaler toutes anomalies ou remarques.</p>
            <%= simple_fields_for :feedback do |p| %>
              <%= p.input :comment, as: :text, :input_html => { 'rows' => 5 } %>
            <% end %>
            <%= f.input :kilometers %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-link" data-bs-dismiss="modal">Annuler</button>
            <%= f.submit "Clôturer ma réservation", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_dashboard_card.html.erb
<div class="col-md-3">
  <div class="dashboard-card border-<%= color %>">
    <div class="dashboard-card-body">
      <div class="row no-gutters align-items-center">
        <div class="col-auto mx-3">
          <i class="fas fa-<%= icon %> dashboard-icon"></i>
        </div>
        <div class="col m-2">
          <div class="dashboard-card-title text-<%= color %>">
            <%= text %>
          </div>
          <div class="dashboard-card-stats"><%= value %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark vh-100 sticky-top" style="width: 280px;">
  <div class="text-center my-3">
    <%= link_to root_path, class: 'text-white text-decoration-none' do %>
      <h3 class="mb-0">ShareTheCar</h3>
    <% end %>
    <small><%= current_user.company.name %></small>
  </div>
  <hr class="mb-3">
  <ul class="nav nav-pills flex-column mb-auto">
    <li>
      <a href="#" class="nav-link text-white" aria-current="page">
        <%= link_to dashboard_path, class: "nav-link text-white #{controller_name == 'pages' && action_name == 'dashboard' ? 'active' : ''}" do %>
          <i class="fas fa-dashboard pe-2"></i> Tableau de bord
        <% end %>
      </a>
    </li>
    <li>
      <%= link_to cars_path, class: "nav-link text-white #{controller_name == 'cars' ? 'active' : ''}" do %>
        <i class="fas fa-car pe-2"></i> Voitures
      <% end %>
    </li>
    <li>
      <%= link_to team_path, class: "nav-link text-white #{controller_name == 'pages' && action_name == 'team' ? 'active' : ''}" do %>
        <i class="fas fa-users pe-2"></i> Rencontrez l'équipe
      <% end %>
    </li>
    <li>
      <%= link_to chatroom_path(current_user.company.chatrooms.first), class: "nav-link text-white #{controller_name == 'chatrooms' && action_name == 'show' ? 'active' : ''}" do %>
        <i class="fas fa-comments pe-2"></i> Discussion
      <% end %>
    </li>
    <hr>
    <li>
      <%= link_to user_path(current_user), class: "nav-link text-white #{controller_name == 'users' && action_name == 'show' && params[:id] == current_user.id.to_s ? 'active' : ''}" do %>
        <i class="fas fa-user pe-2"></i> Mon Profil
      <% end %>
    </li>
  </ul>
</div>

app/views/users/show.html.erb
<% unless @user == current_user %>
  <div class="mt-3 ms-3">
    <%= link_to 'Retour', :back, class: "btn btn-primary" %>
  </div>
<% end %>
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-md-3">
      <div class="card shadow">
        <div class="card-header">
          <% if @user == current_user %>
            <h5 class="card-title m-0">Mes informations</h5>
          <% else %>
            <h5 class="card-title m-0">Informations de <%= @user.full_name%></h5>
          <% end %>
        </div>
        <% if @user.avatar.attached? %>
          <%= cl_image_tag(@user.avatar.key, class: 'card-img-top img-profil', crop: :fill, gravity: :face, alt: "Avatar of " + @user.first_name) %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title text-center"><%= @user.first_name %> <%= @user.last_name %></h5>
          <hr>
          <p class="card-text" style="line-height: 1.7em">
            <i class="fas fa-envelope me-2"></i><%= @user.email %><br />
            <i class="fas fa-phone me-2"></i><%= @user.phone_number %><br />
            <i class="fas fa-building me-2"></i><%= @user.company.name if @user.company %><br />
            <i class="fas fa-calendar-alt me-2"></i>Membre depuis : <%= @user.created_at.strftime("%d/%m/%Y") %>
          </p>
          <% if @user.bio %>
            <hr>
            <p class="card-text"><i class="fa-solid fa-book pe-2"></i> <%= @user.bio %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card shadow mb-3">
        <div class="card-header">
          <% if @user == current_user %>
            <h5 class="card-title m-0">Derniers commentaires sur mes réservations</h5>
          <% else %>
            <h5 class="card-title m-0">Derniers commentaires sur les réservations de <%= @user.full_name%></h5>
          <% end %>
        </div>
        <div class="card-body">
          <% @feedbacks.each do |feedback| %>
            <div class="notification box-shadow border p-0 my-3 align-items-start">
              <div class="col-md-2">
                <%= link_to car_path(feedback.reservation.car) do %>
                  <%= cl_image_tag(feedback.reservation.car.photo.key, class: "feedback-car-img img-fluid w-100", width: 100) if feedback.reservation.car.photo.attached? %>
                <% end %>
              </div>
              <div class="notification-content ml-3 p-3">
                <p><strong><%= feedback.reservation.car.model %></strong></p>
                <p><%= feedback.comment %></p>
                <p><small>Il y a <%= time_ago_in_words(feedback.created_at) %></small></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>